### PR TITLE
[sailfish-office] Open csv files as spreadsheet documents. Fixes JB#4…

### PR DESCRIPTION
**Pull request by mphilippov-omp**
…6745

### CODE REVIEW

**Comment by pvuorela** [comment]
Tried downloading couple test files from 
https://people.sc.fsu.edu/~jburkardt/data/csv/csv.html

...both crashed. How much have you tested these?

**Comment by mphilippov-omp** [comment]
Well, I know it. That's why our first decision was to open CSV files as plain text documents.

I also know you are solving the problem of XLS files. Opening XLS files also crashes application. They both open with Spreadsheet and the mistake is in the same place, so solving your problem will automatically solve mine
________________________________________
От: Pekka Vuorela [notifications@github.com]
Отправлено: 26 августа 2019 г. 13:13
Кому: sailfishos/sailfish-office
Копия: Mikhail Filippov; Author
Тема: Re: [sailfishos/sailfish-office] [sailfish-office] Open csv files as spreadsheet documents. Fixes JB#4… (#136)

Tried downloading couple test files from
https://people.sc.fsu.edu/~jburkardt/data/csv/csv.html

...both crashed. How much have you tested these?

**Comment by dcaliste** [comment]
> Opening XLS files also crashes application.

This [MR in Calligra](https://git.sailfishos.org/mer-core/calligra/merge_requests/11) should correct the problem…

**Comment by mphilippov-omp** [comment]
I know it, thats why I renamed commit messages from Fixes to Contributes.
Thank you, I'll try it
________________________________________
От: Damien Caliste [notifications@github.com]
Отправлено: 28 августа 2019 г. 11:57
Кому: sailfishos/sailfish-office
Копия: Mikhail Filippov; Author
Тема: Re: [sailfishos/sailfish-office] [sailfish-office] Open csv files as spreadsheet documents. Fixes JB#4… (#136)

Opening XLS files also crashes application.

This MR in Calligra<https://git.sailfishos.org/mer-core/calligra/merge_requests/11> should correct the problem…

**Comment by pvuorela** [comment]
Now it doesn't crash, but opens qwidget based import dialog on a separate window, and then choosing something open another qwidget based error dialog and finally crashes. We shouldn't have any QWidget UI shown.

**Comment by mphilippov-omp** [comment]
Yes, I tried it. I haven't seen any error dialogs, just crashing. But when I launch sailfish-office application second time, previosly opened CSV file is displayed
________________________________________
От: Pekka Vuorela [notifications@github.com]
Отправлено: 3 сентября 2019 г. 10:28
Кому: sailfishos/sailfish-office
Копия: Mikhail Filippov; Author
Тема: Re: [sailfishos/sailfish-office] [sailfish-office] Open csv files as spreadsheet documents. Fixes JB#4… (#136)

Now it doesn't crash, but opens qwidget based import dialog on a separate window, and then choosing something open another qwidget based error dialog and finally crashes. We shouldn't have any QWidget UI shown.

**Comment by pvuorela** [comment]
Obsoleted.

**Pull request closed without merging**
