### PR TITLE
[sailfish-office] Use horizontalPageMargin instead of paddingLarge for e...

### PR DESCRIPTION
**Pull request by blammit**
...dge margins.

### CODE REVIEW

**Comment by blammit** [comment]
@martinjones

**Comment by martinjones** [comment]
LGTM, but don't merge until Silica with horizontalPageMargin is released, and update Requires.

**Comment by blammit** [comment]
@VDVsx Could you merge this please?

**Comment by VDVsx** [comment]
Could you please fix merge conflicts and add a bug reference to one of the commits.

**Comment by blammit** [comment]
Declined in favour of https://github.com/sailfishos/sailfish-office/pull/29 (patches merged with #28 to avoid PR conflicts)

**Pull request closed without merging**
