### PR TITLE
[office] Avoid flickering empty state placeholder on app startup. Contributes to JB#42702

### PR DESCRIPTION
**Pull request by jpetrell**

### CODE REVIEW

**Comment by jpetrell** [comment]
Good points. Will fix. :)

**Comment by jpetrell** [comment]
Changed to using ready property. Now ready won't become true until the initial SQL query completes. Previous ready didn't mean much (basically just that componentComplete had happened), also nothing emitted readyChanged() signal.

**Comment by dcaliste** [comment]
Looks good.

**Comment by pvuorela** [comment]
Looking good to me too.

**Pull request merged**
