### PR TITLE
Text and item color fixes

### PR DESCRIPTION
**Pull request by blammit**

### CODE REVIEW

**Comment by blammit** [comment]
@VDVsx

**Comment by VDVsx** [comment]
LGTM, please fix conflicts and then I can merge

**Comment by blammit** [comment]
Thanks, could you merge this one and then I can rebase the other PR on top of this?

**Comment by blammit** [comment]
Oops, hang on a minute

**Comment by blammit** [comment]
Declined in favour of https://github.com/sailfishos/sailfish-office/pull/29 (patches merged with #29 to avoid PR conflicts)

**Pull request closed without merging**
