### PR TITLE
[sailfish-office] Open xml and scv files as text document. Fixes OMP#APPDOC-34

### PR DESCRIPTION
**Pull request by mphilippov-omp**

### CODE REVIEW

**Comment by pvuorela** [comment]
First should have some jolla or mer bug reference for integration.

Second not sure if either of these formats should be opened as text. Both are text based but not necessarily always too much human readable, and CSV is by nature more of spreadsheet anyway.

**Comment by mphilippov-omp** [comment]
First should have some jolla or mer bug reference for integration. 

What do you mean? Your project is on github. It's mirror is on gitlab. Where should I push? 


От: "Pekka Vuorela" <notifications@github.com> 
Кому: "sailfishos/sailfish-office" <sailfish-office@noreply.github.com> 
Копия: "Mikhail Filippov" <m.filippov@omprussia.ru>, "Author" <author@noreply.github.com> 
Отправленные: Понедельник, 19 Август 2019 г 14:51:15 
Тема: Re: [sailfishos/sailfish-office] [sailfish-office] Open xml and scv files as text document. Fixes OMP#APPDOC-34 (#134) 



First should have some jolla or mer bug reference for integration. 

Second not sure if either of these formats should be opened as text. Both are text based but not necessarily always too much human readable, and CSV is by nature more of spreadsheet anyway.

**Comment by pvuorela** [comment]
> What do you mean? Your project is on github. It's mirror is on gitlab. Where should I push?

The PR itself is fine, but i mean that the commit message now refers only some OMP# thing. In order to pass the integration to OBS etc it should have either JB# or MER# reference.

**Comment by mphilippov-omp** [comment]
Spreadsheet? Ok. 
And what format is better for XML in your opinion? 


От: "Pekka Vuorela" <notifications@github.com> 
Кому: "sailfishos/sailfish-office" <sailfish-office@noreply.github.com> 
Копия: "Mikhail Filippov" <m.filippov@omprussia.ru>, "Author" <author@noreply.github.com> 
Отправленные: Понедельник, 19 Август 2019 г 14:51:15 
Тема: Re: [sailfishos/sailfish-office] [sailfish-office] Open xml and scv files as text document. Fixes OMP#APPDOC-34 (#134) 



First should have some jolla or mer bug reference for integration. 

Second not sure if either of these formats should be opened as text. Both are text based but not necessarily always too much human readable, and CSV is by nature more of spreadsheet anyway.

**Comment by pvuorela** [comment]
> And what format is better for XML in your opinion?

First a step backwards: why do you need to, or want to, open xml files? Is there some specific use case?

**Comment by mphilippov-omp** [comment]
Yes. I want to open xml documents via sailfish-office application. 


От: "Pekka Vuorela" <notifications@github.com> 
Кому: "sailfishos" <sailfish-office@noreply.github.com> 
Копия: "Mikhail Filippov" <m.filippov@omprussia.ru>, "Author" <author@noreply.github.com> 
Отправленные: Понедельник, 19 Август 2019 г 15:52:33 
Тема: Re: [sailfishos/sailfish-office] [sailfish-office] Open xml and scv files as text document. Fixes OMP#APPDOC-34 (#134) 





And what format is better for XML in your opinion? 



First a step backwards: why do you need to, or want to, open xml files? Is there some specific use case?

**Comment by pvuorela** [comment]
> Yes. I want to open xml documents via sailfish-office application.

But still the question why do you want to do that? What kind of use case or what kind of xml file would it be that needs to be opened on a mobile device?

**Comment by mphilippov-omp** [comment]
Just to open standard *.xml files. Original xml code should be displayed 


От: "Pekka Vuorela" <notifications@github.com> 
Кому: "sailfishos" <sailfish-office@noreply.github.com> 
Копия: "Mikhail Filippov" <m.filippov@omprussia.ru>, "Author" <author@noreply.github.com> 
Отправленные: Понедельник, 19 Август 2019 г 16:11:22 
Тема: Re: [sailfishos/sailfish-office] [sailfish-office] Open xml and scv files as text document. Fixes OMP#APPDOC-34 (#134) 





Yes. I want to open xml documents via sailfish-office application. 



But still the question why do you want to do that? What kind of use case or what kind of xml file would it be that needs to be opened on a mobile device?

**Comment by pvuorela** [comment]
> Just to open standard *.xml files. Original xml code should be displayed

I may sound like a broken record but: why? Just because a text based file format exists is not necessarily good enough reason to make document viewer open it. Or allowing app to be used for file type could be one thing, but here it would make all xml files on specific locations to be listed as documents, possibly without any real need, thus adding just noise.

**Comment by pvuorela** [comment]
Seems obsoleted by other PRs

**Pull request closed without merging**
